

&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;

## EDUCATION

### Columbia University  \ \ \ \ \ \ \ \ *Biostatistics*  <br /> 
M.S. (Theory and Method Track)\ \ \ \ \ \ Sep 2018 - May 2020

### Columbia University  \ \ \ \ \ \ \ \ *Chemical Engineering*  <br />  
M.S. \ \ \ \ \ \ Sep 2014 - Dec 2015

### Wuhan University  \ \ \ \ \ \ \ \ \ \ *Applied Chemistry *  <br /> 
B.S. \ \ \ \ \ \ Sep 2010 – Jun 2014

&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;

## EXPERIENCE

### Associate Statistician  
Columbia University Medical Center 

+	Applied regression models using demographic, diagnostic and genetic information to identify potential patients or patients' future conditions with R glmnet and dplyr   <br /> 
+	Select best predictive models in classification or regression analysis using AIC or adjusted R2   <br /> 
+	Develop different statistical tests, including two sample t-test, chi-square test and Fisher Exact test, to choose a better treatment, and adjust p values for multiple comparisons   <br />  
+	Calculate sample size through power calculation and adjust p values for multiple comparisons   <br /> 
+	Prepare statistical reports on descriptive analysis and presented with data visualizations (ggplot2 in R)   <br /> 


### Associate Researcher II
Mount Sinai Health System 

+ Supported data mining and exploration to understand disease mechanisms with 200,000+ records   <br /> 
+ Proceed literature review and data mining to generate important feature lists, and used feature selection to reduce model complexity and training time   <br /> 
+ Built predictive models understand the role of different leading factors in neurological diseases using Python numpy, pandas and scikit-learn   <br /> 


&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;



## SKILLS AND CERTIFICATES

+	Computer skills: R, Python, SAS, SQL, Tableau, Excel, MATLAB         <br />
+	Modeling: OLS, Lasso, Ridge, Logistic Regression, SVM, Decision Tree, Random Forest, Boosting, PCA, KNN      <br />
+	Certificates: SAS Certified Advanced Programmer for SAS 9           <br />

&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;



